### ISSUE TITLE
Editar localizacion, datos basicos

### ISSUE THREAD

**Issue by wwjimenez** [minpppst/rsc#2]
Al editar la localizacion, no esta refrescando, por ende no muestra el cambio en el momento, el error que sale internamente es el siguiente:
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
return JSON.parse( data + "" );
jquery.js linea 7522,col 9

**Comment by catu52** [comment]
Ya que existe el botón **"Refrescar"**, este asunto no será una prioridad.

**Comment by catu52** [comment]
El problema era la colocación del atributo ID. En este caso debía mantenerse el ID por defecto **crud-datatable**
