### ISSUE TITLE
Eliminar Localizacion,Proyecto Datos Basicos

### ISSUE THREAD

**Issue by wwjimenez** [minpppst/rsc#3]
Al querer eliminar una localización, los botones de la ventana modal no hacen nada, error interno:
ReferenceError: event is not defined
...!==null){$(buttonElm).click(function(){callback.call(instance,this,event)})}};th...
modalRemote.min.js. linea 1,col 1603

**Comment by catu52** [comment]
Las localizaciones se eliminan correctamente. El error ocurre al intentar eliminar una localización que no existe pero que se muestra debido a que la lista no se ha refrescado.

**Comment by catu52** [comment]
Duplicado.
