### ISSUE TITLE
Eliminar Accion Especifica

### ISSUE THREAD

**Issue by wwjimenez** [minpppst/rsc#4]
Al intentar borrar accion especifica, la ventana modal no le funciona los botones, error interno:
ReferenceError: event is not defined
...!==null){$(buttonElm).click(function(){callback.call(instance,this,event)})}};th...
modalRemote.min.js. linea 1,col 1603

**Comment by catu52** [comment]
Las acciones específicas se eliminan correctamente. No se pudo duplicar el error.
