### ISSUE TITLE
Requerimientos y Proyectos Aprobados

### ISSUE THREAD

**Issue by catu52** [minpppst/rsc#46]
Mostrar en la lista **"Proyecto - Requerimientos"** solo los proyectos aprobados.

**Comment by wwjimenez** [comment]
Carlos para este issue (si es que no lo has hecho) y cuando vengas hablamos con @antoniomonasterio y jamily, para hablar unos temas relacionados.

**Comment by catu52** [comment]
Modificar el modelo para establecer la relación y comprobar la "aprobación" del proyecto.

**proyecto_usuario_asignar**

| Campo | Tipo | Nulo | Otro |
| --- | --- | --- | --- |
| id | int | no | Autoincrement |
| usuario_id | int | no | Llave foránea de usuario |
| proyecto_id | int | no | Llave foránea de proyecto |
| accion_especifica_id | int | no | Llave foránea de acción específica |
