### ISSUE TITLE
Eliminar Proyecto

### ISSUE THREAD

**Issue by wwjimenez** [minpppst/rsc#5]
Al querer eliminar un proyecto, los botones de la ventana modal no hacen nada, error interno:
ReferenceError: event is not defined
...!==null){$(buttonElm).click(function(){callback.call(instance,this,event)})}};th...
modalRemote.min.js. linea 1,col 1603

**Comment by catu52** [comment]
Los proyectos se eliminan correctamente. No se pudo duplicar el error.
