### ISSUE TITLE
Modulo Usuarios (block, set su, borrar, borrar todos, desbloquear todos, bloquear todos)

### ISSUE THREAD

**Issue by wwjimenez** [minpppst/rsc#6]
Al seleccionar algunas de estas opciones: (block, set su, borrar, borrar todos, desbloquear todos, bloquear todos). Se levanta sus respectivos modales, pero los botones dentro de esas modales no realizan actividad alguna. Error interno:
ReferenceError: event is not defined
...!==null){$(buttonElm).click(function(){callback.call(instance,this,event)})}};th...
modalRemote.min.js. linea 1,col 1603

**Comment by catu52** [comment]
El módulo funciona correctamente. No se pudo duplicar el error.
