### ISSUE TITLE
Módulo de Acciones Centralizadas

### ISSUE THREAD

**Issue by catu52** [minpppst/rsc#8]
### Desarrollo del módulo de acciones centralizadas:
- [x] - CRUD Acción Centralizada.
- [x] - Importación Acción Centralizada.
- [x] - Importación Acción Específica.

**Comment by wwjimenez** [comment]
se sube al branch el modulo de acciones especificas, aun tiene algunos detalles pero lo esencial ya esta.

**Comment by catu52** [comment]
Falta la funcionalidad de importar ACC y sus Acciones Específicas.

**Comment by wwjimenez** [comment]
se realizó las importaciones de los respectivos modulos
